// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/otlp/otlpmetric/oconf/options.go.tmpl

// Package oconf provides configuration for the otlpmetric exporters.
package oconf

import (
	"net/http"
	"net/url"
	"time"

	"github.com/karelbilek/opentelemetry/retry"
)

const (
	// DefaultMaxAttempts describes how many times the driver
	// should retry the sending of the payload in case of a
	// retryable error.
	DefaultMaxAttempts int = 5
	// DefaultMetricsPath is a default URL path for endpoint that
	// receives metrics.
	DefaultMetricsPath string = "/v1/metrics"
	// DefaultMaxRequestSize is the default maximum size of a serialized export
	// request, before compression.
	DefaultMaxRequestSize int = 64 * 1024 * 1024
	// DefaultBackoff is a default base backoff time used in the
	// exponential backoff strategy.
	DefaultBackoff time.Duration = 300 * time.Millisecond
	// DefaultTimeout is a default max waiting time for the backend to process
	// each span or metrics batch.
	DefaultTimeout time.Duration = 10 * time.Second
)

type (
	// HTTPTransportProxyFunc is a function that resolves which URL to use as proxy for a given request.
	// This type is compatible with `http.Transport.Proxy` and can be used to set a custom proxy function to the OTLP HTTP client.
	HTTPTransportProxyFunc func(*http.Request) (*url.URL, error)

	SignalConfig struct {
		Endpoint       string
		Insecure       bool
		Headers        map[string]string
		MaxRequestSize int
		Timeout        time.Duration
		URLPath        string
	}

	Config struct {
		// Signal specific configurations
		Metrics SignalConfig

		RetryConfig retry.Config

		// gRPC configurations
		ReconnectionPeriod time.Duration
		ServiceConfig      string
	}
)

// NewHTTPConfig returns a new Config with all settings applied from opts and
// any unset setting using the default HTTP config values.
func NewHTTPConfig(
	endpoint string,
	urlPath string,
	insecure bool,
	headers map[string]string,
	maxRequestSize int,
	timeout time.Duration,
	retry retry.Config,
) Config {
	return Config{
		Metrics: SignalConfig{
			Endpoint:       endpoint,
			URLPath:        urlPath,
			Insecure:       insecure,
			Headers:        headers,
			MaxRequestSize: maxRequestSize,
			Timeout:        timeout,
		},
		RetryConfig: retry,
	}
}
