// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// DO NOT MODIFY. Generated by gotmpl.
// source: internal/shared/otlp/otlptrace/otlpconfig/options.go.tmpl

// Package otlpconfig provides configuration for the otlptrace exporters.
package otlpconfig

import (
	"time"

	"github.com/karelbilek/opentelemetry/retry"
)

const (
	// DefaultTracesPath is a default URL path for endpoint that
	// receives spans.
	DefaultTracesPath string = "/v1/traces"
	// DefaultMaxRequestSize is the default maximum size of a serialized export
	// request, before compression.
	DefaultMaxRequestSize int = 64 * 1024 * 1024
	// DefaultTimeout is a default max waiting time for the backend to process
	// each span batch.
	DefaultTimeout time.Duration = 10 * time.Second
)

type (
	SignalConfig struct {
		Endpoint       string
		Insecure       bool
		Headers        map[string]string
		MaxRequestSize int
		Timeout        time.Duration
		URLPath        string
	}

	Config struct {
		// Signal specific configurations
		Traces SignalConfig

		RetryConfig retry.Config
	}
)

// NewHTTPConfig returns a new Config with all settings applied from opts and
// any unset setting using the default HTTP config values.
func NewHTTPConfig(endpoint string, urlPath string, insecure bool, headers map[string]string, maxRequestSize int, timeout time.Duration,  retry retry.Config) Config {
	cfg := Config{
		Traces: SignalConfig{
			Endpoint:       endpoint,
			Insecure:       insecure,
			Headers:        headers,
			MaxRequestSize: maxRequestSize,
			Timeout:        timeout,
			URLPath:        urlPath,
		}, RetryConfig: retry,
	}
	return cfg
}
